#ifndef ERROR_HANDLING_HPP
#define ERROR_HANDLING_HPP

#define OUT_OF_BOUNDS_COORD 		1
#define OUT_OF_BOUNDS_START_COORD 	2
#define OUT_OF_BOUNDS_END_COORD 	3
#define PATHFINDING_STUCK			4
#define PATHFINDING_OUT_OF_BOUNDS	5
#define UNOPTIMAL_MAP_GENERATED		6
#define PATH_INSIDE_ROOM			7

#endif